name = "worker-rust"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

kv_namespaces = [
  { binding = "RADICAL_TICKET_KV", id = "373b8520dc6b42dbb4be2b7b929aa5cc" }
]

[build]
command = "cargo install -q worker-build && worker-build --release"
